FROM bitnami/suitecrm:latest

# Set environment variables for DigitalOcean App Platform
ENV SUITECRM_DATABASE_HOST=${DB_HOST}
ENV SUITECRM_DATABASE_PORT_NUMBER=${DB_PORT}
ENV SUITECRM_DATABASE_USER=${DB_USERNAME}
ENV SUITECRM_DATABASE_PASSWORD=${DB_PASSWORD}
ENV SUITECRM_DATABASE_NAME=${DB_DATABASE}
ENV SUITECRM_USERNAME=${SUITECRM_ADMIN_USER}
ENV SUITECRM_PASSWORD=${SUITECRM_ADMIN_PASSWORD}
ENV SUITECRM_EMAIL=${SUITECRM_ADMIN_EMAIL}
ENV SUITECRM_HOST=${SUITECRM_HOST}
ENV SUITECRM_ENABLE_HTTPS=yes
ENV SUITECRM_EXTERNAL_HTTP_PORT_NUMBER=80
ENV SUITECRM_EXTERNAL_HTTPS_PORT_NUMBER=443

# App Platform expects port 8080
ENV APACHE_HTTP_PORT_NUMBER=8080
ENV APACHE_HTTPS_PORT_NUMBER=8443

# Expose the port
EXPOSE 8080 8443

# Use non-root user
USER 1001

# Start SuiteCRM
CMD ["/opt/bitnami/scripts/suitecrm/run.sh"]